server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huwe0314/springcloud-config.git #GitHub上面的git仓库名字
          force-pull: true #设置强行pull拉取
          username: huwe0314
          password:  huwe950314 #填写你自己密码
          ####搜索目录
          search-paths:
          - springcloud-config
      ####读取分支
      label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
